# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-07 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('video', models.FileField(upload_to='video/LectureVideo')),
                ('image', models.ImageField(upload_to='images/Lectureimage')),
                ('introduce', models.TextField(blank=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=500)),
            ],
        ),
    ]
