# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-07 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturevideo',
            name='slug',
            field=models.SlugField(default='test', max_length=500),
        ),
    ]
