# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-08 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0003_remove_lecturevideo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturevideo',
            name='user_like',
            field=models.ManyToManyField(blank=True, related_name='video_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
