# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-09 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_lecturevideo_user_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='lecturevideo',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='video.Classify'),
        ),
    ]
